name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  unit:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/unittest
  static:
    name: "Static code analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/flake8
